
import {fontFamily} from './fonts'

  const Images = {
    splash_img: require('./icons/splash_img.png'),
    quivio_img: require('./icons/Quivio.png'),
    q_img: require('./icons/Q.png'),
    analy: require('./icons/analy.png'),
    clock: require('./icons/clock.png'),
    flask: require('./icons/flask.png'),
    eye : require('./icons/eye.png'),
    mail : require('./icons/mail.png'),
    pass : require('./icons/pass.png'),
    arrow : require('./icons/Arrow.png'),
    quiv : require('./icons/Qui.png'),
    cross:  require('./icons/close.png'),
    check:  require('./icons/check.png'),
    errorLock:require('./icons/errorlock.png'),
    exclaimatory :require('./icons/Exclaim.png'),
    Imgbg : require('./icons/Imgbg.png'),
    Splashbg: require('./icons/Landing.png'),
    home : require('./icons/home.png'),
    menu :  require('./icons/menu.png'),
    favorite :  require('./icons/favorite.png'),
    account :  require('./icons/account.png'),
    SecureImg : require('./icons/SecureImg.png'),
    passcode : require('./icons/passcode.png'),
    linkaccount : require('./icons/linkaccount.png'),
    secure : require('./icons/secure.png'),
    backarrow: require('./icons/backarrow.png'),
    alert: require('./icons/alert.png'),
    shield : require('./icons/Shield.png'),
    Verify : require('./icons/Verify.png'),
    Link :  require('./icons/Link.png'),
    key:require('./icons/Verify.png'),
    bell: require('./icons/bell.png'),
    message: require('./icons/message.png'),
    tutorialImg : require('./icons/tutorialImg.png'),
    setting: require('./icons/setting.png'),
    time: require('./icons/time.png'),
    speaker:  require('./icons/speaker.png'),
    users :  require('./icons/users.png'),
    smallarrow: require('./icons/smallarrow.png'),
    logout : require('./icons/logout.png'),
    logouted:  require('./icons/logouted.png'),
    slide : require('./icons/slide.png'),
    illustration : require('./icons/lustration.png'),
    profile : require('./icons/profile.png'),
    avatar :require('./icons/avatar.png'),
    camera : require('./icons/camera.png'),
    gallery : require('./icons/gallery.png'),
    arrows : require('./icons/arrows.png'),
    calendar : require('./icons/calendar.png'),
    downarrow : require('./icons/downarrow.png'),
    male : require('./icons/male.png'),
    female : require('./icons/female.png'),
  };
  
  export {Images,fontFamily};